PENDING: usb: typec: ucsi_glink: Search current directory for headers
As specified in samples/trace_events/Makefile:

If you include a trace header outside of include/trace/events
then the file that does the #define CREATE_TRACE_POINTS must
have that tracer file in its main search path. This is because
define_trace.h will include it, and must be able to find it from
the include/trace directory.

Without this the following compilation error is seen:
In file included from drivers/usb/typec/ucsi/ucsi_glink_trace.h:40,
                 from drivers/usb/typec/ucsi/ucsi_glink.c:19:
./include/trace/define_trace.h:95:42: fatal error: ./ucsi_glink_trace.h:
No such file or directory
   95 | #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)
      |                                          ^
compilation terminated.

Fixes: cb234eb39bf5 ("Merge "PENDING: usb: typec: ucsi_glink: Add ftrace support for ucsi_glink transactions"").

Change-Id: I2bde4d5914c41d896acb2b1a4cd2959febc9f053
Signed-off-by: Umang Chheda <quic_uchheda@quicinc.com>
(cherry picked from commit ea5073c0c0cba0a84d5b85eaa379a0c39b45bdb9)
Signed-off-by: Masahiro Yamada <masahiro.yamada@canonical.com>