UBUNTU [Config] set CONFIG_DEFAULT_MMAP_MIN_ADDR=32768
BugLink: https://bugs.launchpad.net/bugs/2115712 (CONFIG_MMAP_MIN_ADDR should 32768)

One of the regresstion testing case from ubuntu_qrt_kernel_security fails:

ubuntu@rb3gen2:~/qa-regression-testing/scripts$ sudo python3 ./test-kernel-security.py -v  KernelSecurityConfigTest.test_170_config_security_default_mmap_min_addr
Running test: './test-kernel-security.py' distro: 'Ubuntu 24.04' kernel: '6.8.0-1047.47 (Ubuntu 6.8.0-1047.47-qcom 6.8.12)' arch: 'arm64' init: 'systemd' uid: 0/0 SUDO_USER: 'ubuntu')
test_170_config_security_default_mmap_min_addr (__main__.KernelSecurityConfigTest.test_170_config_security_default_mmap_min_addr)
CONFIG_DEFAULT_MMAP_MIN_ADDR ... (32768) FAIL

======================================================================
FAIL: test_170_config_security_default_mmap_min_addr (__main__.KernelSecurityConfigTest.test_170_config_security_default_mmap_min_addr)
CONFIG_DEFAULT_MMAP_MIN_ADDR
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/qa-regression-testing/scripts/./test-kernel-security.py", line 2534, in test_170_config_security_default_mmap_min_addr
    self.assertEqual(self._get_config(config), expected,
AssertionError: '4096' != '32768'
- 4096
+ 32768
 : config DEFAULT_MMAP_MIN_ADDR was expected to bet set to 32768

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)

Signed-off-by: Masahiro Yamada <masahiro.yamada@canonical.com>